# Generated by Django 3.0.8 on 2020-07-10 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': '二手房', 'verbose_name_plural': '二手房'},
        ),
        migrations.AlterModelOptions(
            name='house',
            options={'verbose_name': '二手房', 'verbose_name_plural': '二手房'},
        ),
        migrations.AlterField(
            model_name='house',
            name='area',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='面积(平方米)'),
        ),
        migrations.AlterField(
            model_name='house',
            name='direction',
            field=models.CharField(choices=[('e', '东'), ('s', '南'), ('w', '西'), ('n', '北')], max_length=2, verbose_name='朝向'),
        ),
        migrations.AlterField(
            model_name='house',
            name='floor',
            field=models.CharField(choices=[('l', '低楼层'), ('m', '中楼层'), ('h', '高楼层')], max_length=1, verbose_name='楼层'),
        ),
        migrations.AlterField(
            model_name='house',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=8, verbose_name='价格(万元)'),
        ),
    ]
