# Generated by Django 3.0.8 on 2020-07-12 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0004_auto_20200712_2208'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='bedroom',
            field=models.IntegerField(choices=[(1, '1室'), (2, '2室'), (3, '3室'), (4, '4室')], verbose_name='房型'),
        ),
    ]
