# Generated by Django 3.0.8 on 2020-07-12 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0005_auto_20200712_2214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='house',
            name='area_class',
            field=models.CharField(blank=True, choices=[('1', '<50平米'), ('2', '50-70平米'), ('3', '70-90平米'), ('4', '90-140平米'), ('5', '>140平米')], max_length=1, null=True, verbose_name='面积'),
        ),
        migrations.AlterField(
            model_name='house',
            name='bedroom',
            field=models.CharField(choices=[('1', '1室1厅'), ('2', '2室1厅'), ('3', '3室1厅'), ('4', '4室2厅')], max_length=1, verbose_name='房型'),
        ),
    ]
