# Generated by Django 3.0.8 on 2020-07-13 13:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('house', '0006_auto_20200712_2219'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='community',
            options={'verbose_name': '小区', 'verbose_name_plural': '小区'},
        ),
    ]
